### ISSUE TITLE
Can't  creat Convolution , Polling and SoftmaxOutput operator

### ISSUE THREAD

**Issue by zhubuntu** [hjk41/MxNet.cpp#14] opened 2016-01-25 08:40 UTC
I'm trying to build a CNN net with this C++ Warper.This is the code to test.This code can compile right .But when i run it ,the program will crash at 
```
Symbol conv1 = Convolution("conv1", data, conv1_w, conv1_b, mshadow::Shape2(5, 5), 20);
```

```
Symbol pool1 = Pooling("pool1", data, mshadow::Shape2(2, 2)
		, PoolingPoolType::max, mshadow::Shape2(2, 2));
```
and
```
Symbol lenet = SoftmaxOutput("softmax", data, sm_l);
```
,both the Release and Debuge mode.
The error information is
```
0x00007FFFAD0CA96D (libmxnet.dll) (MxnetTestApp.exe 中)处有未经处理的异常:  0xC0000005:  读取位置 0xFFFFFFFFFFFFFFFF 时发生访问冲突。
```
```cpp 
	    auto data = Symbol::Variable("data");
		auto conv1_w = Symbol::Variable("CW1");
		auto conv1_b = Symbol::Variable("CB1");
		auto fc1_w = Symbol::Variable("FW1");
		auto fc1_b = Symbol::Variable("FB1");
		auto sm_l = Symbol::Variable("SML");
		Symbol conv1 = Convolution("conv1", data, conv1_w, conv1_b, mshadow::Shape2(5, 5), 20);
		Symbol tanh1 = Activation("tanh1", data, ActivationActType::tanh);
		Symbol pool1 = Pooling("pool1", data, mshadow::Shape2(2, 2)
		, PoolingPoolType::max, mshadow::Shape2(2, 2));
		Symbol flatten = Flatten("flatten", data);
		Symbol fc1 = FullyConnected("fc1", data, fc1_w, fc1_b, 500);
		Symbol lenet = SoftmaxOutput("softmax", data, sm_l);
```
I also try the [lenet.cpp in the example](https://github.com/hjk41/MxNet.cpp/blob/master/example/lenet.cpp),same error.

**Comment by zhangchen-qinyinghua** [comment] 2016-01-25 10:38
@zhubuntu 
This is caused by this:
https://github.com/dmlc/mshadow/issues/93

Please use the latest mshadow heads to replace the current ones.
https://github.com/dmlc/mshadow/tree/master/mshadow

**Comment by zhubuntu** [comment] 2016-01-25 11:30
@zhangchen-qinyinghua Thanks,I replace the mshadow heads,
The SoftmaxOutput runs well, but Convolution and Polling operation still have problem.

And I also try rebuild the libmxnet.dll from the latest source.

**Comment by zhangchen-qinyinghua** [comment] 2016-01-26 13:55
@zhubuntu
I can't recreate your problem.

Please make sure you have replaced the mshadow heads with the following( not the one withiin mxnet):
https://github.com/dmlc/mshadow/blob/master/mshadow/tensor_blob.h

**Comment by zhangchen-qinyinghua** [comment] 2016-01-26 13:55
@zhubuntu
I can't recreate your problem.

Please make sure you have replaced the mshadow heads with the following( not the one withiin mxnet):
https://github.com/dmlc/mshadow/blob/master/mshadow/tensor_blob.h

**Comment by zhubuntu** [comment] 2016-01-26 14:45
@zhangchen-qinyinghua OK,Thanks for your help.I think the tensor_blob.h is same with the one in mxnet source code. So i just download the latest mxnet source and rebuild the libmxnet.dll.
But I'll go Home for winter vacation so It'll cost sometime for me to try what you say.Feel very sorry for this.

**Comment by zhangchen-qinyinghua** [comment] 2016-01-28 09:27
@zhubuntu 
It's OK.
I will make it work with the old headers.

**Comment by zhangchen-qinyinghua** [comment] 2016-02-13 02:01
@zhubuntu 
The problem should be solved by @hjk41 .
I will close the issue for now.

**Closed by zhangchen-qinyinghua** 2016-02-13 02:01 UTC
